version: '3.7'
services:
  app:
    build: .
    ports:
      - 7860:7860
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: crm
      MYSQL_ROOT_PASSWORD: 
